export enum EMineActions {
  VER_MINAS = 'VER_MINAS',
  CREAR_MINA = 'CREAR_MINA',
  EDITAR_MINA = 'EDITAR_MINA',
  ACTIVAR_MINA = 'ACTIVAR_MINA',
  ELIMINAR_MINA = 'ELIMINAR_MINA'
}

export enum ESupplierContactActions {
  VER_CONTACTOS = 'VER_CONTACTOS',
  CREAR_CONTACTO = 'CREAR_CONTACTO',
  EDITAR_CONTACTO = 'EDITAR_CONTACTO',
  ACTIVAR_CONTACTO = 'ACTIVAR_CONTACTO',
  ELIMINAR_CONTACTO = 'ELIMINAR_CONTACTO'
}

export enum ENotificationConfigActions {
  VER_CONFIGURACION_NOTIFICACIONES = 'VER_CONFIGURACION_NOTIFICACIONES',
  CREAR_CONFIGURACION_NOTIFICACION = 'CREAR_CONFIGURACION_NOTIFICACION',
  ACTIVAR_CONFIGURACION_NOTIFICACION = 'ACTIVAR_CONFIGURACION_NOTIFICACION',
  ELIMINAR_CONFIGURACION_NOTIFICACION = 'ELIMINAR_CONFIGURACION_NOTIFICACION'
}

export enum EMineralSendActions {
  VER_ORDEN_ENVIO_BASCULA = 'VER_ORDEN_ENVIO_BASCULA',
  CREAR_ORDEN_ENVIO_BASCULA = 'CREAR_ORDEN_ENVIO_BASCULA',
  EDITAR_ORDEN_ENVIO_BASCULA = 'EDITAR_ORDEN_ENVIO_BASCULA',
  CANCELAR_ORDEN_ENVIO_BASCULA = 'CANCELAR_ORDEN_ENVIO_BASCULA'
}