export enum ECurrentShiftActions {
  ABRIR_TURNO = 'ABRIR_TURNO',
  CERRAR_TURNO = 'CERRAR_TURNO',
  AGREGAR_PERSONAL_TURNO = 'AGREGAR_PERSONAL_TURNO',
  ELIMINAR_PERSONAL_TURNO = 'ELIMINAR_PERSONAL_TURNO',

}

export enum EShiftConfigActions {
  AGREGAR_PERSONAL_CONFIGURACION_TURNO = 'AGREGAR_PERSONAL_CONFIGURACION_TURNO',
  ELIMINAR_PERSONAL_CONFIGURACION_TURNO = 'ELIMINAR_PERSONAL_CONFIGURACION_TURNO',
  EDITAR_PERSONAL_CONFIGURACION_TURNO = 'EDITAR_PERSONAL_CONFIGURACION_TURNO',
}

export enum EDryingActions {
  VER_ORDENES_DE_ENVIO = 'VER_ORDENES_DE_ENVIO',
  VER_BIG_BAGS = 'VER_BIG_BAGS',
  CREAR_BIG_BAG = 'CREAR_BIG_BAG',
  GENERAR_ORDEN_DE_ENVIO = 'GENERAR_ORDEN_DE_ENVIO',
}